services:
  api:
    build:
      context: ..
      dockerfile: deployments/docker/Dockerfile.api
    ports:
      - "8080:8080"
    environment:
      - REDIS_ADDR=redis:6379
    depends_on:
      - redis

  worker:
    build:
      context: ..
      dockerfile: deployments/docker/Dockerfile.worker
    environment:
      - REDIS_ADDR=redis:6379
    depends_on:
      - redis

  results:
    build:
      context: ..
      dockerfile: deployments/docker/Dockerfile.results
    environment:
      - REDIS_ADDR=redis:6379
      - POSTGRES_DSN=user=postgres password=postgres host=postgres dbname=leetcode sslmode=disable
    depends_on:
      - redis
      - postgres
  
  redis:
    image: redis:8.4-alpine
    ports:
      - "6380:6379"

  postgres:
    image: postgres:16.11-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=leetcode
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: