apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: redis-scaledobject-free
  namespace: leetcode-judge
spec:
  scaleTargetRef:
    name: worker-free
  
  minReplicaCount: 1
  maxReplicaCount: 10
  pollingInterval: 15
  cooldownPeriod: 30

  triggers:
  - type: redis
    metadata:
      address: redis-svc.leetcode-judge.svc.cluster.local:6379
      listName: free-submissions
      listLength: "7"