apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: leetcode-judge
spec:
  resources:
    requests:
      storage: "50Mi"
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
