apiVersion: v1
kind: Service
metadata:
  name: api-preview
  namespace: leetcode-judge
  labels:
    app: api
spec:
  selector:
    app: api
  ports:
  - port: 80
    nodePort: 30081
    targetPort: 8080
  type: NodePort